vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        auth:
          token: $SOURCE_TOKEN
      better_stack_http_metrics_sink: ~
    sources:
      better_stack_kubernetes_metrics_nodes: ~
      better_stack_kubernetes_metrics_pods: ~
    transforms:
      better_stack_kubernetes_metrics_nodes_parser: ~
      better_stack_kubernetes_metrics_pods_parser: ~

metrics-server:
  enabled: false
