# config for Minikube with disabled TLS
vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        auth:
          token: $SOURCE_TOKEN
      better_stack_http_metrics_sink:
        auth:
          token: $SOURCE_TOKEN
    sources:
      better_stack_kubernetes_metrics_nodes:
        tls:
          verify_certificate: false
          verify_hostname: false
      better_stack_kubernetes_metrics_pods:
        tls:
          verify_certificate: false
          verify_hostname: false

metrics-server:
  args:
    - --kubelet-insecure-tls
