name: End-to-end test

on:
  push:
    paths:
      - .github/**
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  test-last-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
      - name: Check cluster pods
        run: kubectl get pods -A

      - name: 1. Add Helm repository
        run: helm repo add betterstack-logs https://betterstackhq.github.io/logs-helm-chart && helm repo update
      - name: 2. Set up Helm chart
        run: sed 's/$SOURCE_TOKEN/${{ secrets.HELM_E2E_TEST_SOURCE_TOKEN }}/g' .github/helm-values-template.yaml > values.yaml
      - name: 3. Deploy the chart
        run: helm install betterstack-logs betterstack-logs/betterstack-logs -f values.yaml

      - name: Wait for the chart to be ready
        run: kubectl wait --for=condition=available deployment/betterstack-logs-metrics-server --timeout=60s
      - name: Check cluster pods
        run: kubectl get pods -A

      - name: Deploy Hello World pod
        run: kubectl run hello-world --image=hello-world --wait
      - name: Check cluster pods
        run: kubectl get pods -A

      - name: Wait for a while with the running pods
        run: sleep 30

